export type Section =
	| 'NORMATIVA E LEGISLAZIONE'
	| 'AERODINAMICA'
	| 'PRONTO SOCCORSO'
	| 'FISIOPATOLOGIA DEL VOLO'
	| 'METEOROLOGIA E AEROLOGIA'
	| 'STRUMENTI'
	| 'TECNICA DI PILOTAGGIO'
	| 'MATERIALI'
	| 'SICUREZZA DEL VOLO';

export const pointsBySection: Record<Section, number> = {
	'NORMATIVA E LEGISLAZIONE': 0,
	AERODINAMICA: 0,
	'PRONTO SOCCORSO': 0,
	'FISIOPATOLOGIA DEL VOLO': 0,
	'METEOROLOGIA E AEROLOGIA': 0,
	STRUMENTI: 0,
	'TECNICA DI PILOTAGGIO': 0,
	MATERIALI: 0,
	'SICUREZZA DEL VOLO': 0
};

export const numberOfQuestionsBySection: Record<Section, number> = {
	'NORMATIVA E LEGISLAZIONE': 4,
	AERODINAMICA: 8,
	'PRONTO SOCCORSO': 1,
	'FISIOPATOLOGIA DEL VOLO': 1,
	'METEOROLOGIA E AEROLOGIA': 6,
	STRUMENTI: 1,
	'TECNICA DI PILOTAGGIO': 5,
	MATERIALI: 1,
	'SICUREZZA DEL VOLO': 3
};
